### PR TITLE
Removes controls, removes vuetify references.

### LINKED ISSUE #5: Make 'index' into prop, drop vuetify dependency.
I think this package would be easier to use and maintain without being locked to a Vuetify version and the couple of trivial controls it provides.  

Make "index" a prop and remove controls.

### PR DESCRIPTION
**Pull request by subdavis**
Adds the dist folder so we can install from github, since I see a lot of projects that function this way.

I think this repo is low-traffic enough to make the tradeoff worthwhile.  We can stick with npm deployments, but this solution seemed like 1 less thing to have to deal with.

Don't really care either way though.

fixes #5

### CODE REVIEW

**Comment by zachmullen** [comment]
Can we separate these two changes? I'm not wild about checking large build artifacts into the repo that may change drastically with each commit.

**Comment by subdavis** [comment]
That's fair, we can stick with deploying to NPM.  Would you like to add me to the npm project or deploy it yourself?

**Comment by zachmullen** [comment]
I'll add you

**Comment by zachmullen** [comment]
Looks like you have write access already.

**Review by zachmullen — APPROVED** [review]

**Pull request merged**
